services:
  - type: web
    name: issue-reporting-system-backend
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
